spring.application.name=curtis-backend
server.port=3001

# Microsoft OAuth
microsoft.client-id=fecfeca1-ffe2-43d4-a07c-45525efe771b
microsoft.tenant-id=b12e8dea-6f3d-43a1-8913-4cf3fb1834c3
microsoft.redirect-uri=http://localhost:3001/redirect

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/curtisdb
spring.datasource.username=curtisuser
spring.datasource.password=curtispass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
